name: CI
on: push

jobs:     
  test:
    runs-on: ubuntu-latest
    steps:

    - name: set env
      run: echo "first step sets env MY_SECRET to ${MY_SECRET}"
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}

    - name: inspect env
      run: env
